// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCuIUwtazCoVzM4ngjTS1ar8_1oE5-eXQ',
    appId: '1:726845108727:web:f607bfeaaadd47954cbef2',
    messagingSenderId: '726845108727',
    projectId: 'smart-inhaler-db',
    authDomain: 'smart-inhaler-db.firebaseapp.com',
    storageBucket: 'smart-inhaler-db.firebasestorage.app',
    measurementId: 'G-17WMNG9QDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkGif0FrbyuDpJ-wA92EI5ITS7aBJYfTQ',
    appId: '1:726845108727:android:dfcc48cc6591e9d94cbef2',
    messagingSenderId: '726845108727',
    projectId: 'smart-inhaler-db',
    storageBucket: 'smart-inhaler-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYXzSO3IJpZlx1EAKf8ATz0lwN2cmKZY',
    appId: '1:726845108727:ios:8cd148f00476cf644cbef2',
    messagingSenderId: '726845108727',
    projectId: 'smart-inhaler-db',
    storageBucket: 'smart-inhaler-db.firebasestorage.app',
    iosBundleId: 'com.example.smartInhaler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYXzSO3IJpZlx1EAKf8ATz0lwN2cmKZY',
    appId: '1:726845108727:ios:8cd148f00476cf644cbef2',
    messagingSenderId: '726845108727',
    projectId: 'smart-inhaler-db',
    storageBucket: 'smart-inhaler-db.firebasestorage.app',
    iosBundleId: 'com.example.smartInhaler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCuIUwtazCoVzM4ngjTS1ar8_1oE5-eXQ',
    appId: '1:726845108727:web:05e0c805634158204cbef2',
    messagingSenderId: '726845108727',
    projectId: 'smart-inhaler-db',
    authDomain: 'smart-inhaler-db.firebaseapp.com',
    storageBucket: 'smart-inhaler-db.firebasestorage.app',
    measurementId: 'G-EDYMJ5BK69',
  );
}
